// Real browser, isolated API fixtures. No existing conversation or model is modified.
import assert from "node:assert/strict";
import { pathToFileURL } from "node:url";
import fs from "node:fs/promises";
const { chromium } = await import(pathToFileURL(process.env.NEGUS_PLAYWRIGHT_MODULE).href);
const browser = await chromium.launch({ channel: "msedge", headless: true });
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } });
const page = await context.newPage();
page.setDefaultTimeout(12000);
const errors = [], calls = [];
page.on("pageerror", error => errors.push(error.stack || error.message));
const root = "D:/goal-browser-fixture";
const makeSession = id => ({ threadId: id, source: "codex", title: id, cwd: root, updatedAt: new Date().toISOString(), messageCount: 0, messages: [], model: "fixture" });
const sessions = [makeSession("goal-fixture"), makeSession("other-fixture")];
const project = { id: "p", name: "Goal test", kind: "personal", root, conversations: sessions.map(s => ({ ...s, id: s.threadId })) };
const status = id => ({ type: "execution_status", threadId: id, turnId: null, phase: "idle", active: false, label: "", detail: "", commentary: "", activities: [], updatedAt: new Date().toISOString(), startedAt: null });
let currentGoal = null, heldPause = null, heldClear = null, holdPause = false, holdClear = false, failGet = false;
const goal = (state = "active", objective = "Browser goal") => ({ threadId: sessions[0].threadId, objective, status: state, tokenBudget: null, tokensUsed: 120, timeUsedSeconds: 8, createdAt: 100, updatedAt: Math.floor(Date.now()/1000) });
await context.addInitScript(() => {
  window.__sources = [];
  window.__eventId = 1;
  window.EventSource = class {
    static CLOSED = 2;
    readyState = 1;
    constructor() { window.__sources.push(this); setTimeout(() => { this.onopen?.({}); this.onmessage?.({ data: JSON.stringify({ type: "connected", eventId: 1 }), lastEventId: "" }); }, 10); }
    close() { this.readyState = 2; window.__sources = window.__sources.filter(s => s !== this); }
  };
  window.__emit = data => { const id = String(++window.__eventId); window.__sources.forEach(s => s.onmessage?.({ data: JSON.stringify(data), lastEventId: id })); };
});
await page.route("**/api/**", async route => {
  const url = new URL(route.request().url()), method = route.request().method();
  const body = method === "GET" ? null : route.request().postDataJSON();
  calls.push({ path: url.pathname, method, body });
  let data = {};
  if (url.pathname === "/api/session/goal") {
    if (method === "GET") {
      if (failGet) return route.fulfill({ status: 503, contentType: "application/json", body: "{}" });
      data = { goal: url.searchParams.get("threadId") === "other-fixture" ? null : currentGoal };
    } else if (method === "POST") {
      const next = { ...(currentGoal || goal()), ...body, updatedAt: Math.floor(Date.now()/1000) };
      if (holdPause && body.status === "paused") { heldPause = () => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ goal: next }) }); return; }
      currentGoal = next; data = { goal: next };
    } else {
      if (holdClear) { heldClear = () => route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ goal: null }) }); return; }
      currentGoal = null; data = { goal: null };
    }
  } else if (url.pathname === "/api/project") data = { name: "Goal test", root, mode: "interactive" };
  else if (url.pathname === "/api/project-directory") data = { projects: [project] };
  else if (url.pathname === "/api/sessions") data = sessions;
  else if (url.pathname === "/api/session") data = sessions.find(s => s.threadId === url.searchParams.get("threadId")) || sessions[0];
  else if (url.pathname === "/api/execution-status") data = status(url.searchParams.get("threadId"));
  else if (url.pathname.includes("queue")) data = { items: [] };
  else if (url.pathname === "/api/model-channels") data = { channels: [] };
  else if (url.pathname === "/api/session/model") data = { model: "fixture", modelProvider: "current", reasoningEffort: "low" };
  else if (url.pathname === "/api/models") data = [{ id: "fixture", model: "fixture", displayName: "Fixture", supportedReasoningEfforts: [], isDefault: true }];
  else if (url.pathname.includes("user-input")) data = { request: null };
  else if (url.pathname.includes("context")) data = { type: "context_status", threadId: "goal-fixture", model: "fixture", reasoningEffort: "low", usedTokens: 0, contextWindow: 1000, percentage: 0, autoCompactThreshold: 80, phase: "idle", message: "", updatedAt: new Date().toISOString() };
  await route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify(data) });
});
const emit = async next => { currentGoal = next; await page.evaluate(value => window.__emit({ type: "goal_status", threadId: "goal-fixture", goal: value }), next); };
const visible = async label => page.getByText(label, { exact: true }).first().waitFor({ timeout: 10000 });
const tick = () => new Promise(resolve => setTimeout(resolve, 50));
const waitHeld = async which => { for (let n=0;n<100 && !which();n++) await tick(); assert.ok(which(), "request reached fixture"); };
try {
  await page.goto("http://127.0.0.1:9360/?view=conversation&thread=goal-fixture", { waitUntil: "domcontentloaded" });
  const input = page.getByPlaceholder("给 Codex 发送指令");
  await input.waitFor();
  await input.fill("/goal Browser goal");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await visible("进行中的目标");
  assert.ok(calls.some(c => c.path === "/api/session/goal" && c.method === "POST" && c.body.objective === "Browser goal"));
  assert.equal(calls.filter(c => c.path === "/api/session/message").length, 0, "/goal must never generate an ordinary message turn");
  console.log("PASS direct native goal creation");
  const before = await page.locator('[aria-label="目标状态"]').innerText();
  await page.waitForTimeout(1200);
  assert.notEqual(await page.locator('[aria-label="目标状态"]').innerText(), before, "active duration ticks without server events");
  await page.getByRole("button", { name: "暂停目标", exact: true }).click();
  await visible("已暂停的目标");
  await page.getByRole("button", { name: "恢复目标", exact: true }).click();
  await visible("进行中的目标");
  for (const [state,label,resumable] of [["blocked","目标已停滞",true],["usageLimited","目标使用受限",true],["budgetLimited","目标受限",false]]) {
    await emit(goal(state)); await visible(label);
    assert.equal(await page.getByRole("button", { name: "恢复目标", exact: true }).count(), resumable ? 1 : 0);
  }
  await emit(goal("active"));
  await page.getByRole("button", { name: "停止当前任务", exact: true }).click();
  await visible("已暂停的目标");
  console.log("PASS six-state controls, live elapsed time and stop between turns");
  await emit(goal("paused"));
  await page.getByRole("button", { name: "编辑目标", exact: true }).click();
  await page.getByRole("textbox", { name: "目标", exact: true }).fill("Edited goal");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  await visible("进行中的目标");
  assert.equal(currentGoal.objective, "Edited goal");
  assert.equal(currentGoal.status, "active");
  await page.getByRole("dialog", { name: "编辑目标", exact: true }).waitFor();
  await visible("刚刚更新");
  assert.equal(await page.getByRole("button", { name: "保存", exact: true }).isDisabled(), true);
  await page.getByRole("textbox", { name: "目标", exact: true }).fill("Unsaved change");
  await page.getByRole("button", { name: "还原", exact: true }).click();
  assert.equal(await page.getByRole("textbox", { name: "目标", exact: true }).innerText(), "Edited goal");
  assert.equal(await page.locator("dialog:modal").count(), 0, "goal editor must not lock the conversation");
  await page.getByRole("button", { name: "关闭目标编辑", exact: true }).click();
  console.log("PASS saved editor remains open, reports update time and reverts to saved objective");
  await input.fill("/goal Replacement");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await page.getByRole("dialog", { name: "替换当前目标吗？" }).waitFor();
  await page.getByRole("button", { name: "取消", exact: true }).click();
  assert.equal(currentGoal.objective, "Edited goal");
  assert.equal(await input.inputValue(), "/goal Replacement");
  await input.fill("");
  console.log("PASS edit reactivates and replacement confirmation preserves draft");
  await emit(goal("active"));
  holdPause = true;
  await page.getByRole("button", { name: "暂停目标", exact: true }).click();
  await waitHeld(() => heldPause);
  await emit(goal("complete")); await visible("已达成目标");
  await heldPause(); holdPause = false;
  await visible("已达成目标");
  assert.equal(await page.getByRole("button", { name: "暂停目标", exact: true }).count(), 0);
  console.log("PASS late pause response cannot undo completion");
  await emit(goal("active","Old goal"));
  holdClear = true;
  await page.getByRole("button", { name: "清除目标", exact: true }).click();
  await waitHeld(() => heldClear);
  await emit(goal("active","New goal"));
  await heldClear(); holdClear = false;
  await visible("New goal");
  console.log("PASS late clear response cannot hide new goal");
  await page.evaluate(() => { const url = new URL(location.href); url.searchParams.set("thread","other-fixture"); url.searchParams.set("conversation","employee-other"); history.pushState({}, "", url); window.dispatchEvent(new PopStateEvent("popstate")); });
  await page.waitForTimeout(250);
  assert.equal(await page.locator('[aria-label="目标状态"]').count(), 0, "other thread must not display previous goal");
  const clearsBefore = calls.filter(c => c.path === "/api/session/goal" && c.method === "DELETE").length;
  await emit(goal("complete", "Background completion"));
  for (let n = 0; n < 100 && calls.filter(c => c.path === "/api/session/goal" && c.method === "DELETE").length === clearsBefore; n++) await tick();
  assert.equal(calls.filter(c => c.path === "/api/session/goal" && c.method === "DELETE").length, clearsBefore + 1, "background completion clears its native goal");
  assert.equal(await page.locator('[aria-label="\u76ee\u6807\u72b6\u6001"]').count(), 0, "background completion cannot appear in selected thread");
  assert.equal(calls.filter(c => c.path === "/api/session/goal" && c.method === "DELETE").at(-1).body.conversationId, undefined, "background cleanup must not inherit the selected employee conversation");
  await emit(goal("active", "New goal"));
  console.log("PASS background completion clears native goal without contaminating selected thread");
  await page.evaluate(() => { const url = new URL(location.href); url.searchParams.set("thread","goal-fixture"); url.searchParams.delete("conversation"); history.pushState({}, "", url); window.dispatchEvent(new PopStateEvent("popstate")); });
  await visible("New goal");
  currentGoal = goal("paused", "Changed while disconnected");
  await page.evaluate(() => window.dispatchEvent(new Event("online")));
  await visible("Changed while disconnected");
  await visible("已暂停的目标");
  console.log("PASS thread isolation and reconnect rehydrates actual goal");
  await emit(goal("active", "New goal"));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "runtime/goal-mobile.png" });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), "no mobile horizontal overflow");
  await page.setViewportSize({ width: 1280, height: 900 });
  await page.screenshot({ path: "runtime/goal-desktop.png" });
  currentGoal = goal("paused", "Reopened paused goal");
  await page.reload({ waitUntil: "domcontentloaded" });
  await page.getByRole("dialog", { name: "恢复已暂停的目标吗？" }).waitFor();
  await page.getByRole("button", { name: "保持暂停", exact: true }).click();
  assert.equal(currentGoal.status, "paused");
  await page.getByRole("button", { name: "恢复目标", exact: true }).click();
  await visible("进行中的目标");
  console.log("PASS reopening paused goal asks before resuming");
  const longGoal = { ...goal("active", "Read the Codex goal objective file at C:/test/goal-objective.md before continuing."), displayObjective: "Readable long objective" };
  await emit(longGoal);
  await visible("Readable long objective");
  const { displayObjective, ...nativeGoal } = longGoal;
  await emit({ ...nativeGoal, status: "complete" });
  await visible("Readable long objective");
  console.log("PASS native completion retains expanded long objective");
  await page.evaluate(value => window.__emit({ type: "goal_status", threadId: "background-employee", conversationId: "employee-owned", goal: value }), { ...goal("complete", "Employee complete"), threadId: "background-employee" });
  for (let n = 0; n < 100 && !calls.some(c => c.path === "/api/session/goal" && c.method === "DELETE" && c.body.threadId === "background-employee"); n++) await tick();
  const employeeClear = calls.find(c => c.path === "/api/session/goal" && c.method === "DELETE" && c.body.threadId === "background-employee");
  assert.equal(employeeClear.body.threadId, "background-employee");
  assert.equal(employeeClear.body.conversationId, "employee-owned");
  console.log("PASS employee background cleanup preserves its owned conversation scope");
  await emit(goal("paused", "**Bold objective**\n\n- first task\n- second task\n\n[Reference](https://example.com)\n\n\`\`\`js\nconst done = true;\n\`\`\`"));
  await page.getByRole("button", { name: "编辑目标", exact: true }).click();
  const rich = page.getByRole("textbox", { name: "目标", exact: true });
  await rich.locator("strong").filter({ hasText: "Bold objective" }).waitFor();
  assert.equal(await rich.locator("li").count(), 2);
  assert.equal(await rich.locator("a").getAttribute("href"), "https://example.com");
  assert.match(await rich.locator("pre").innerText(), /const done = true/);
  await rich.click();
  await rich.press("Control+End");
  await rich.press("Control+A");
  await rich.press("Backspace");
  await rich.press("Control+B");
  await rich.pressSequentially("Formatted objective");
  await rich.press("Control+B");
  await page.getByRole("button", { name: "保存", exact: true }).click();
  for (let i = 0; i < 100 && currentGoal?.objective !== "**Formatted objective**"; i++) await tick();
  assert.equal(currentGoal.objective, "**Formatted objective**", "rich formatting serializes into native goal Markdown");
  assert.equal(currentGoal.status, "active");
  await page.getByRole("button", { name: "关闭目标编辑", exact: true }).click();
  console.log("PASS rich goal editor restores bold, lists, links and fenced code");
  failGet = true;
  await page.reload({ waitUntil: "domcontentloaded" });
  await page.getByRole("alert").filter({ hasText: "503" }).first().waitFor();
  assert.deepEqual(errors, []);
  console.log("PASS mobile/desktop layout and visible query failure; no browser exceptions");
} catch (error) { console.error(error); await page.screenshot({ path: "runtime/goal-failure.png" }); console.error(JSON.stringify({ url: page.url(), errors, body: (await page.locator("body").innerText()).slice(0,1800), calls: calls.slice(-12) })); throw error; } finally { await browser.close(); }
