import React from 'react';
import {interpolate,useCurrentFrame} from 'remotion';
import {C,Frame,Reveal,Logo,Arrow,clamp} from '../design';
export const Workspace=()=>{const f=useCurrentFrame();const text='帮我梳理这个项目的下一步。';return <Frame kicker="ONE PLACE. LESS FRICTION." number="03">
 <Reveal delay={3} style={{position:'absolute',left:160,top:175}}><h1 style={{fontSize:83,letterSpacing:-3,fontWeight:600,margin:0}}>一个入口，连接工作。</h1></Reveal>
 <div style={{position:'absolute',left:260,top:340,width:1400,height:590,background:'#1C2721',border:'1px solid #3B5144',borderRadius:24,overflow:'hidden',boxShadow:'0 35px 70px #0005',opacity:interpolate(f,[12,32],[0,1],clamp),translate:`0 ${interpolate(f,[12,45],[55,0],clamp)}px`}}>
 <div style={{height:58,borderBottom:'1px solid #34463B',display:'flex',alignItems:'center',padding:'0 26px',gap:9}}>{['#83968A','#617568','#455A4C'].map(s=><span key={s} style={{width:10,height:10,borderRadius:'50%',background:s}}/>)}<span style={{marginLeft:20,fontSize:20,color:'#A9B9AF'}}>negus / 工作空间</span></div>
 <div style={{display:'flex',height:532}}><div style={{width:245,padding:'34px 26px',background:'#17211B',borderRight:'1px solid #34463B'}}><div style={{fontSize:18,color:'#819B8A',letterSpacing:3,marginBottom:30}}>PROJECTS</div>{['品牌项目','产品迭代','日常灵感'].map((s,i)=><div key={s} style={{fontSize:26,marginBottom:18,padding:'15px 14px',borderRadius:10,background:i===0?'#30483B':'transparent',color:i===0?C.accent:'#A7B9AC'}}>{s}</div>)}</div>
 <div style={{flex:1,padding:'30px 38px'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2 style={{margin:0,fontSize:32,fontWeight:500}}>品牌项目</h2><span style={{fontSize:18,color:C.muted}}>项目 · 对话 · 成果</span></div><div style={{marginTop:24,display:'flex',gap:22}}>
 <div style={{flex:1,background:'#22342A',borderRadius:16,padding:'26px 28px'}}><div style={{fontSize:18,color:'#91B59D',marginBottom:18}}>和助理一起推进</div><div style={{height:58,fontSize:27,color:C.paper}}>{text.slice(0,Math.floor(interpolate(f,[43,98],[0,text.length],clamp)))}<span style={{opacity:f<100&&f%24<12?1:0,color:C.accent}}>▎</span></div><div style={{opacity:interpolate(f,[102,120],[0,1],clamp),borderTop:'1px solid #3D5748',paddingTop:20,fontSize:24,lineHeight:1.9,color:'#D5E2D9'}}>目标、进展、下一步。<br/>让讨论有据可循。</div></div>
 <div style={{width:320,border:'1px solid #405548',borderRadius:16,padding:24}}><div style={{fontSize:18,color:'#93AB9D',marginBottom:24}}>项目成果</div>{['方案文档','设计素材','迭代记录'].map((s,i)=><div key={s} style={{fontSize:24,padding:'14px 0',borderTop:'1px solid #354B3D',display:'flex',justifyContent:'space-between',opacity:interpolate(f,[66+i*12,85+i*12],[0,1],clamp)}}>{s}<Arrow color={C.accent} size={24}/></div>)}</div></div>
 <div style={{height:62,marginTop:22,borderRadius:13,border:'1px solid #496251',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 20px',color:'#8FA698',fontSize:21}}><span>继续说说你的想法…</span><div style={{background:C.accent,borderRadius:9,width:40,height:40,display:'flex',alignItems:'center',justifyContent:'center'}}><Arrow size={25}/></div></div>
 </div></div></div>
 </Frame>};
